- name: create celery group
  group: name=celery state=present

- name: create celery user
  user: name=celery group=celery state=present

- name: install supervisor
  apt: pkg=supervisor state=installed

- name: create supervisord config folder
  file: dest=/etc/supervisor state=directory owner=root

- name: copy supervisor program config
  template: src=supervisor.conf dest=/etc/supervisor/conf.d/{{ app_name }}-celery.conf
  register: supervisor_conf
  notify: restart celery

- shell: supervisorctl reread
  when: supervisor_conf.changed

- shell: supervisorctl update
  when: supervisor_conf.changed

- name: ensure supervisor is running
  service: name=supervisor state=started enabled=yes
